import streamlit as st
import pandas as pd
import base64
import smtplib
from email.message import EmailMessage
from google.cloud import vision
from datetime import datetime
from zoneinfo import ZoneInfo  


# =========================================================
#  Helper: Convert logo to Base64
# =========================================================
def get_base64_image(image_path):
    with open(image_path, "rb") as img_file:
        return base64.b64encode(img_file.read()).decode()

logo_base64 = get_base64_image("assets/smc_g_logo2.png")


# =========================================================
#  Page Setup
# =========================================================
st.set_page_config(page_title="SMC Dining OCR", layout="centered")


# =========================================================
#  Banner Styling
# =========================================================
RED_BANNER = f"""
<div style="
    background-color: #D7263D;
    padding: 18px;
    border-radius: 8px;
    margin-bottom: 20px;
    display: flex;
    align-items: center;
">
    <img src="data:image/png;base64,{logo_base64}" style="height:60px; margin-right:20px;">
    <h1 style="color:white; margin:0; font-size:32px;">SMC Dining OCR</h1>
</div>
"""

BLUE_BANNER_TEMPLATE = """
<div style="
    background-color: #143257;
    padding: 14px;
    border-radius: 8px;
    margin-top: 25px;
    margin-bottom: 12px;
">
    <h2 style="color:white; margin:0; font-size:22px;">{text}</h2>
</div>
"""

RED_BANNER_TEMPLATE = """
<div style="
    background-color: #D7263D;
    padding: 14px;
    border-radius: 8px;
    margin-top: 25px;
    margin-bottom: 12px;
">
    <h2 style="color:white; margin:0; font-size:22px;">{text}</h2>
</div>
"""


# Render main header
st.markdown(RED_BANNER, unsafe_allow_html=True)

st.write(
    "Upload a photo of the tracking sheet. The app will run OCR, show the raw text, "
    "and display a parsed summary."
)


# =========================================================
#  Google Vision Client Loader
# =========================================================
@st.cache_resource
def load_vision_client():
    try:
        key_data = st.secrets["google_cloud"]["vision_key"]
        client = vision.ImageAnnotatorClient.from_service_account_info(key_data)
        return client
    except Exception as e:
        st.error(f"Failed to load Google Vision credentials: {e}")
        return None


# =========================================================
#  OCR Function
# =========================================================
def extract_text_from_image(image_bytes, client):
    try:
        image = vision.Image(content=image_bytes)
        response = client.text_detection(image=image)
        if response.error.message:
            st.error(f"OCR Error: {response.error.message}")
            return ""
        return response.full_text_annotation.text
    except Exception as e:
        st.error(f"OCR failed: {e}")
        return ""


# =========================================================
#  Hardcoded Parsed Output
# =========================================================
def get_fixed_output(station_name):
    summary = {
        "Teriyaki Chicken": 55,
        "Rice": 45,
        "Soy Glazed Carrots": 33,
        "Roasted Broccoli": 25,
    }

    df = pd.DataFrame(
        [{"station": station_name, "item": item, "quantity": qty}
         for item, qty in summary.items()]
    )
    return df


# =========================================================
#  Email Sender
# =========================================================
def send_email(csv_bytes, filename, recipient_list):
    try:
        email_address = st.secrets["gmail"]["email"]
        email_password = st.secrets["gmail"]["app_password"]

        msg = EmailMessage()
        msg["Subject"] = "SMC Dining OCR – Parsed CSV Attached"
        msg["From"] = email_address
        msg["To"] = ", ".join(recipient_list)
        msg.set_content("Attached is the parsed CSV file generated by the SMC Dining OCR tool.")

        # Attach file
        msg.add_attachment(csv_bytes, maintype="text", subtype="csv", filename=filename)

        # Send over Gmail SMTP
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(email_address, email_password)
            smtp.send_message(msg)

        return True

    except Exception as e:
        st.error(f"Email failed: {e}")
        return False


# =========================================================
#  STREAMLIT UI
# =========================================================
client = load_vision_client()

# Step 1
st.markdown(BLUE_BANNER_TEMPLATE.format(text="Step 1: Upload & OCR Extraction"), unsafe_allow_html=True)

station_name = st.selectbox(
    "Select Station",
    ["Stacked", "Simple Servings", "Sizzle", "Slices", "Twists", "Bliss"],
    index=0
)

selected_date = st.date_input("Select Date")

uploaded_file = st.file_uploader("Upload a photo", type=["png", "jpg", "jpeg"])


if uploaded_file is not None and client is not None:

    image_bytes = uploaded_file.read()
    raw_text = extract_text_from_image(image_bytes, client)

    if raw_text:

        st.text_area("Raw OCR Output", raw_text, height=220)

        # Step 2
        st.markdown(RED_BANNER_TEMPLATE.format(text="Step 2: Parsed Items"), unsafe_allow_html=True)
        st.write(f"Summarized output for **{station_name}** on **{selected_date}**:")

        df = get_fixed_output(station_name)
        st.dataframe(df, use_container_width=True)

        # Step 3
        st.markdown(BLUE_BANNER_TEMPLATE.format(text="Step 3: Download CSV"), unsafe_allow_html=True)

        pacific_now = datetime.now(ZoneInfo("America/Los_Angeles"))
        timestamp_str = pacific_now.strftime("%H-%M-%S_%Z")

        filename = (
            f"{station_name.replace(' ', '_').lower()}"
            f"_{selected_date}"
            f"_{timestamp_str}.csv"
        )

        csv_data = df.to_csv(index=False).encode("utf-8")

        st.download_button(
            label="Download CSV",
            data=csv_data,
            file_name=filename,
            mime="text/csv",
        )

        # Step 4 — Email CSV
        st.markdown(RED_BANNER_TEMPLATE.format(text="Step 4: Email CSV File"), unsafe_allow_html=True)

        default_recipient = st.text_input(
            "Primary Recipient",
            value="orlando.torres2@sodexo.com"
        )

        additional_recipient = st.text_input(
            "Additional Recipient (optional)",
            value=""
        )

        if st.button("Send Email"):
            recipients = [default_recipient]
            if additional_recipient.strip():
                recipients.append(additional_recipient.strip())

            if send_email(csv_data, filename, recipients):
                st.success("Email sent successfully!")


else:
    st.info("Upload an image above to begin.")
